create table teachers(
  teacher_id bigint generated by default as identity primary key,
  username text unique not null,
  password text not null,
  name text
);

create table students(
  student_id bigint generated by default as identity primary key,
  name text not null,
  face_embedding JSONB,
  voice_embedding JSONB
);
-- | student_id | name | face_embedding    | voice_embedding   |
-- | ---------- | ---- | ----------------- | ----------------- |
-- | 1          | Faiz | [0.12, 0.98, ...] | [0.22, 0.11, ...] |


create table subjects(
  subject_id bigint generated by default as identity primary key,
  subject_code text not null,
  name text default 'UNKNOWN',
  section text default 'N/A',
  teacher_id bigint references teachers(teacher_id) on delete set null 
  -- when teacher delete ✔ Subject still exists ✔ Only teacher link removed
  -- | subject_code | name | teacher_id |
  -- | ------------ | ---- | ---------- |
  -- | CS101        | DBMS | NULL       |
);

create table subject_students(
  subject_id bigint references subjects(subject_id) on delete cascade,
  -- If a subject is deleted → automatically delete related rows here
  student_id bigint references students(student_id) on delete cascade,
  -- If student is deleted → remove all their subject links
  primary key(subject_id, student_id)
);

create table attendence_logs(
  id bigint generated by default as identity primary key,
  timestamp timestamptz default now(),  
  -- timestamptz --> timestamp with timezone📌 Example: 2026-04-25 10:30:00+05:30
  subject_id bigint references subjects(subject_id) on delete cascade,
  student_id bigint references students(student_id) on delete cascade,
  is_present bool default true
);

